import fs from 'node:fs';
import vm from 'node:vm';

const catalogueSource = fs.readFileSync(new URL('../data/catalogue.js', import.meta.url), 'utf8');
const sandbox = { window: {} };
vm.runInNewContext(catalogueSource, sandbox, { filename: 'catalogue.js' });
const records = sandbox.window.NIGHT_INDEX_RECORDS;

async function wikiCover(record) {
  const response = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(record.wiki)}`);
  const data = response.ok ? await response.json() : null;
  return data?.thumbnail?.source || data?.originalthumbnail?.source || '';
}

async function tvMazeCover(record) {
  const response = await fetch(`https://api.tvmaze.com/singlesearch/shows?q=${encodeURIComponent(record.coverSearch)}`);
  const data = response.ok ? await response.json() : null;
  return data?.image?.original || data?.image?.medium || '';
}

async function openLibraryCover(record) {
  const response = await fetch(`https://openlibrary.org/search.json?q=${encodeURIComponent(record.coverSearch)}&limit=5`);
  const data = response.ok ? await response.json() : null;
  const coverId = data?.docs?.find(item => item.cover_i)?.cover_i;
  return coverId ? `https://covers.openlibrary.org/b/id/${coverId}-L.jpg` : '';
}

async function aniListCover(record) {
  const type = record.type === 'manga' ? 'MANGA' : 'ANIME';
  const response = await fetch('https://graphql.anilist.co', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
    body: JSON.stringify({
      query: 'query ($search: String, $type: MediaType) { Media(search: $search, type: $type) { coverImage { extraLarge large } } }',
      variables: { search: record.coverSearch, type }
    })
  });
  const data = response.ok ? await response.json() : null;
  return data?.data?.Media?.coverImage?.extraLarge || data?.data?.Media?.coverImage?.large || '';
}

async function resolveCover(record) {
  if (record.poster) return { src: record.poster, provider: 'IMDb' };
  const primary = await wikiCover(record);
  if (primary) return { src: primary, provider: 'Wikimedia' };
  if (record.type === 'series') return { src: await tvMazeCover(record), provider: 'TVmaze' };
  if (record.type === 'book') return { src: await openLibraryCover(record), provider: 'Open Library' };
  if (record.type === 'anime' || record.type === 'manga') return { src: await aniListCover(record), provider: 'AniList' };
  return { src: '', provider: 'fallback' };
}

const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
async function resolveWithRetry(record) {
  for (let attempt = 0; attempt < 3; attempt += 1) {
    try {
      const cover = await resolveCover(record);
      if (cover.src) return cover;
    } catch {
      // A provider may temporarily throttle this build; retry before failing the output.
    }
    await delay(350 * (attempt + 1));
  }
  return { src: '', provider: 'fallback' };
}

const covers = {};
const queue = [...records];
const workers = Array.from({ length: 6 }, async () => {
  while (queue.length) {
    const record = queue.shift();
    covers[record.id] = await resolveWithRetry(record);
  }
});
await Promise.all(workers);

const unresolved = Object.entries(covers).filter(([, cover]) => !cover.src).map(([id]) => id);
if (unresolved.length) throw new Error(`Missing cover URLs: ${unresolved.join(', ')}`);

const output = `// Generated by scripts/build-covers.mjs. Do not edit by hand.\nwindow.NIGHT_INDEX_COVERS = ${JSON.stringify(covers, null, 2)};\n`;
fs.writeFileSync(new URL('../data/covers.js', import.meta.url), output);
console.log(`Wrote ${Object.keys(covers).length} cover records to data/covers.js`);
